### POST request to create new Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name" : "Danger Pollardd",
    "email" : "rdfndgjfhwddddsd@example.com",
    "address": "123 main street",
    "dateOfBirth" : "1995-09-09",
    "registeredDate": "2026-11-28"
}
###