### POST request to create new Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name" : "Kziefsdfsdfsdron Pollard",
    "email" : "randdxo1ddddsdf2@example.com",
    "address": "123 main street",
    "dateOfBirth" : "1995-09-09",
    "registeredDate": "2024-11-28"
}
###