spring.application.name=patient-service
spring.h2.console.path=/h2-console

spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.driver-class-name=${DB_CLASS:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:admin_viewer}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

logging.level.root=info

server.port=4000

